'use strict';
const autocompleteData = {
   "Wing chair": null,
   "TV stand": null,
   "Sofa": null,
   "Cushion": null,
   "Telephone": null,
   "Television": null,
   "Speaker": null,
   "End table": null,
   "Tea set": null,
   "Fireplace": null,
   "Remote": null,
   "Fan": null,
   "Floor lamp": null,
   "Carpet": null,
   "Table": null,
   "Blinds": null,
   "Curtains": null,
   "Picture": null,
   "Vase": null,
   "Grandfather clock": null,
   "Bedside Table": null,
   "Bed": null,
   "Linens": null,
   "Pillow": null,
   "Pillow Cases": null,
   "Lamps": null,
   "Alarm Clock": null,
   "Chair": null,
   "Nightlight": null,
   "Rugs": null,
   "Dresser": null,
   "Throws (blankets)": null,
   "Nightstand": null,
   "Smoke Detector": null,
   "Wall Picture": null,
   "Duvet": null,
   "Apple": null,
   "Banana": null,
   "Orange": null,
   "Coriander": null,
   "Kale": null,
   "Watermelon": null,
   "Mango": null,
   "Noodles": null,
   "Juice": null,
   "Dal": null,
   "Black beans": null,
   "Kidney beans": null,
   "Coconuts": null,
   "Dark Chocolate": null,
   "Bread": null,
   "Chocolate": null,
   "Yogurt": null,
   "Milk": null,
   "Cilantro": null,
   "Sooji fine": null,
   "Saaru powder": null,
   "Pineapple": null,
   "Almond": null,
   "Carrot": null,
   "Brocolli": null,
   "JavaScript": null,
   "Lisp": null,
   "Perl": null,
   "PHP": null,
   "Python": null,
   "Ruby": null,
   "Scala": null,
   "Scheme": null,
   "Apricot": null,
   "Artichoke": null,
   "Asian Pear": null,
   "Asparagus": null,
   "Atemoya": null,
   "Avocado": null,
   "Bamboo Shoots": null,
   "Bean Sprouts": null,
   "Beans": null,
   "Beets": null,
   "Belgian Endive": null,
   "Bell Peppers": null,
   "Bitter Melon": null,
   "Blackberries": null,
   "Blueberries": null,
   "Bok Choy": null,
   "Boniato": null,
   "Boysenberries": null,
   "Broccoflower": null,
   "Broccoli": null,
   "Brussels Sprouts": null,
   "Cabbage": null,
   "Cactus Pear": null,
   "Cantaloupe": null,
   "Carambola": null,
   "Carrots": null,
   "Casaba Melon": null,
   "Cauliflower": null,
   "Celery": null,
   "Chayote": null,
   "Cherimoya": null,
   "Cherries": null,
   "Collard Greens": null,
   "Corn": null,
   "Cranberries": null,
   "Cucumber": null,
   "Dates": null,
   "Dried Plums": null,
   "Eggplant": null,
   "Endive": null,
   "Escarole": null,
   "Feijoa": null,
   "Fennel": null,
   "Figs": null,
   "Garlic": null,
   "Gooseberries": null,
   "Grapefruit": null,
   "Grapes": null,
   "Green Beans": null,
   "Green Onions": null,
   "Greens": null,
   "Guava": null,
   "Hominy": null,
   "Honeydew Melon": null,
   "Horned Melon": null,
   "Iceberg Lettuce": null,
   "Jerusalem Artichoke": null,
   "Jicama": null,
   "Kiwifruit": null,
   "Kohlrabi": null,
   "Kumquat": null,
   "Leeks": null,
   "Lemons": null,
   "Lettuce": null,
   "Lima Beans": null,
   "Limes": null,
   "Longan": null,
   "Loquat": null,
   "Lychee": null,
   "Madarins": null,
   "Malanga": null,
   "Mandarin Oranges": null,
   "Mangos": null,
   "Mulberries": null,
   "Mushrooms": null,
   "Napa": null,
   "Nectarines": null,
   "Okra": null,
   "Onion": null,
   "Oranges": null,
   "Papayas": null,
   "Parsnip": null,
   "Passion Fruit": null,
   "Peaches": null,
   "Pears": null,
   "Peas": null,
   "Peppers": null,
   "Persimmons": null,
   "Plantains": null,
   "Plums": null,
   "Pomegranate": null,
   "Potatoes": null,
   "Prickly Pear": null,
   "Prunes": null,
   "Pummelo": null,
   "Pumpkin": null,
   "Quince": null,
   "Radicchio": null,
   "Radishes": null,
   "Raisins": null,
   "Raspberries": null,
   "Red Cabbage": null,
   "Rhubarb": null,
   "Romaine Lettuce": null,
   "Rutabaga": null,
   "Shallots": null,
   "Snow Peas": null,
   "Spinach": null,
   "Sprouts": null,
   "Squash": null,
   "Strawberries": null,
   "String Beans": null,
   "Sweet Potato": null,
   "Tangelo": null,
   "Tangerines": null,
   "Tomatillo": null,
   "Tomato": null,
   "Turnip": null,
   "Ugli Fruit": null,
   "Water Chestnuts": null,
   "Watercress": null,
   "Waxed Beans": null,
   "Yams": null,
   "Yellow Squash": null,
   "Yuca/Cassava": null,
   "Zucchini Squash": null,
   "Buffet": null,
   "Chairs": null,
   "Draperies": null,
   "Window Hardware": null,
   "Mirrors": null,
   "Clocks": null,
   "China": null,
   "Crystal": null,
   "Silver ": null,
   "Flatware": null,
   "Paintings ": null,
   "Appliances ": null,
   "Cabinets and Contents ": null,
   "Wall Shelving": null,
   "China Cabinet": null,
   "Stove/Oven": null,
   "Refrigerator": null,
   "Dishwasher": null,
   "Utensils": null,
   "Cutlery": null,
   "Dishes ": null,
   "Glassware": null,
   "Freezer": null,
   "Microwave": null,
   "Rotisserie": null,
   "Food Processor": null,
   "Mixer": null,
   "Blender": null,
   "Radio": null,
   "Clock": null,
   "Ceiling Fan": null,
   "Cookbooks": null,
   "Foods": null,
   "Garbage Disposal": null,
   "Liquors": null,
   "Pots and Pans": null,
   "Small Appliances": null,
   "Washer": null,
   "Dryer": null,
   "Ironing Board": null,
   "Iron": null,
   "Closet Contents ": null,
   "Bookcases": null,
   "Books": null,
   "Compact Discs ": null,
   "Computer": null,
   "Couches": null,
   "Desk": null,
   "Drapes": null,
   "Electronic Games ": null,
   "Entertainment Centre": null,
   "Fireplace Equipment ": null,
   "Games/Toys ": null,
   "Hobby Equipment ": null,
   "Piano": null,
   "Pictures": null,
   "Tables": null,
   "VCR": null,
   "DVDs ": null,
   "DVD Player": null,
   "Tapes ": null,
   "Window Air Conditioner": null,
   "Whirlpool": null,
   "Hamper": null,
   "Hair Dryer": null,
   "Scale": null,
   "Shower Curtain": null,
   "Electric Razors": null,
   "Medications ": null,
   "Humidifier": null,
   "Pictures ": null,
   "Furniture ": null,
   "Mattress/Box Spring": null,
   "Bedding": null,
   "Dressers": null,
   "Radios": null,
   "Nightstands": null,
   "Men’s Clothing ": null,
   "Women’s Clothing ": null,
   "Children’s Clothing ": null,
   "Shoes ": null,
   "Handbags ": null,
   "Vacuum Cleaner": null,
   "Auto Equipment ": null,
   "Bicycles": null,
   "Garden Furniture": null,
   "Garden Tools": null,
   "Lawn Furniture": null,
   "Power Tools ": null,
   "Sports Equipment ": null,
   "Storage Shelving": null,
   "Furniture": null,
   "Trunks": null,
   "Cameras": null,
   "Golf Equipment": null,
   "Ski Equipment": null,
   "Boating Equipment": null,
   "Paint Set": null,
   "Pool Table": null,
   "Exercise Equipment": null,
   "Hunting Equipment": null,
   "Fishing Equipment": null,
   "Stamp Collection": null,
   "Carving Set": null,
   "Sewing Machine": null,
   "Bowling Equipment": null,
   "Camping Equipment": null,
   "Games": null,
   "Ice Skating Equipment": null,
   "Tennis Equipment": null,
   "Home Computer": null,
   "Modem": null,
   "Hard Drive": null,
   "Scanner": null,
   "Printer": null,
   "Fax Machine": null,
   "Antiques": null,
   "Bracelets": null,
   "Brooches": null,
   "Central Air Conditioning Unit": null,
   "Central Heating Unit": null,
   "Earrings": null,
   "Fine Art": null,
   "Furs": null,
   "Hobby Collections": null,
   "Necklaces": null,
   "Other Jewellery": null,
   "Rings": null,
   "Watches": null,
   "Sculptures": null,
   "Handbags": null,
 };